### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by davidevincenzi** [fabioalmeida/FAAutoLayout#14]
Hi

great library! Could you please add carthage support?

**Comment by fabioalmeida** [comment]
Hello Davide. Thank you for your feedback! I'll try to add the support as soon as possible. I'll let you know as soon as it is done. Cheers.

**Comment by fabioalmeida** [comment]
Cathage support added! Just check the README for further details. 

Thank you for your feedback 👍

**Comment by davidevincenzi** [comment]
Thanks Fabio for your really fast support!
